# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


[[main]]
  name = "SBOL Data Model"
  url = "/DataModel"
  weight = 20
  identifier = "dom-id"

[[main]]
  name = "About SBOL"
  url = "/DataModel-about"
  weight = 5
  parent = "dom-id"

[[main]]
  name = "Data Model Specification"
  url = "/DataModel-Specification"
  weight = 10
  parent = "dom-id"

[[main]]
  name = "Libraries"
  url = "/libraries"
  weight = 15
  parent = "dom-id"

[[main]]
  name = "SBOL Ontology"
  url = "/ontology"
  weight = 20
  parent = "dom-id"

[[main]]
  name = "Examples"
  url = "/DataModel-Examples"
  weight = 35
  parent = "dom-id"

[[main]]
  name = "SBOL Visual"
  url = "/visual"
  weight = 25
  identifier = "visual-id"

[[main]]
  name = "About SBOL Visual"
  url = "/visual-about"
  weight = 5
  parent = "visual-id"

[[main]]
  name = "Visual Specification"
  url = "/visual-specification"
  weight = 10
  parent = "visual-id"

[[main]]
  name = "Glyphs"
  url = "/visual-glyphs"
  weight = 15
  parent = "visual-id"

[[main]]
  name = "SBOL Visual Ontology"
  url = "/sbol-visual-ontology"
  weight = 20
  parent = "visual-id"

[[main]]
  name = "Examples from papers"
  url = "/visual-examples"
  weight = 25
  parent = "visual-id"

[[main]]
  name = "10 Years of SBOL Visual"
  url = "/sbolv-10-years"
  weight = 30
  parent = "visual-id"

[[main]]
  name = "Ecosystem"
  url = "/ecosystem"
  weight = 30
  identifier = "ecosystem-id"

[[main]]
  name = "Applications"
  url = "/applications"
  weight = 5
  parent = "ecosystem-id"

 [[main]]
  name = "Converter"
  url = "https://converter.sbolstandard.org/"
  weight = 10
  parent = "ecosystem-id"

[[main]]
  name = "Validator"
  url = "https://validator.sbolstandard.org/"
  weight = 15
  parent = "ecosystem-id" 

[[main]]
  name = "Publications"
  url = "/publication"
  weight = 40

[[main]]
  name = "News"
  url = "/news"
  weight = 45
  identifier = "news-id"

[[main]]
  name = "Announcements"
  url = "/post"
  weight = 5
  parent = "news-id"

[[main]]
  name = "Blog"
  url = "/blog"
  weight = 10
  parent = "news-id"



[[main]]
  name = "Community"
  url = "/community"
  weight = 50
  identifier = "community-id"

[[main]]
  name = "About"
  url = "/community"
  weight = 5
  parent = "community-id"

[[main]]
  name = "Meetings"
  url = "/community-meetings"
  weight = 10
  parent = "community-id"

[[main]]
  name = "Outreach"
  url = "/community-outreach"
  weight = 15
  parent = "community-id"

[[main]]
  name = "Leadership"
  url = "/community-leadership"
  weight = 18
  parent = "community-id"

[[main]]
  name = "Governance"
  url = "/community-governance"
  weight = 20
  parent = "community-id"

[[main]]
  name = "SBOL Industrial Consortium"
  url = "/sbol-industrial"
  weight = 25
  parent = "community-id"

# Footer Links

[[footer]]
  name = "Contact Us"
  url = "/contact"
  weight = 10

[[footer]]
  name = "FAQ"
  url = "/faq"
  weight = 20

[[footer]]
  name = "Stack Exchange"
  url = "https://bioinformatics.stackexchange.com/questions/tagged/sbol"
  weight = 30

[[footer]]
  name = "View Source"
  url = "https://github.com/SynBioDex/SbolStandardWebsite"
  weight = 40

[[footer]]
  name = "Community Media"
  url = "https://github.com/SynBioDex/Community-Media"
  weight = 50

[[footer]]
  name = "Report an Issue"
  url = "https://github.com/SynBioDex/SbolStandardWebsite/issues"
  weight = 60
