# Navigation Links

[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "Learn SBOL"
  weight = 20
  identifier = "learn-id"

[[main]]
  name = "What is SBOL?"
  url = "/datamodel-about/"
  parent = "learn-id"
  weight = 1

[[main]]
  name = "What is SBOL Visual?"
  url = "/visual-about/"
  parent = "learn-id"
  weight = 2

[[main]]
  name = "FAQ"
  url = "/faq/"
  parent = "learn-id"
  weight = 3

[[main]]
  name = "Blog"
  url = "/post/"
  parent = "learn-id"
  weight = 4

[[main]]
  name = "Specifications"
  weight = 30
  identifier = "spec-id"

[[main]]
  name = "Data Model Specification"
  url = "/DataModel-Specification/"
  parent = "spec-id"
  weight = 1

[[main]]
  name = "Visual Specification"
  url = "/visual-specification/"
  parent = "spec-id"
  weight = 2

[[main]]
  name = "Ontology"
  url = "/ontology/"
  parent = "spec-id"
  weight = 3

[[main]]
  name = "Examples"
  url = "/DataModel-Examples/"
  parent = "spec-id"
  weight = 4

[[main]]
  name = "Tools & Resources"
  weight = 40
  identifier = "tools-id"

[[main]]
  name = "Applications"
  url = "/applications/"
  parent = "tools-id"
  weight = 1

[[main]]
  name = "Libraries"
  url = "/libraries/"
  parent = "tools-id"
  weight = 2

[[main]]
  name = "Converter"
  url = "https://converter.sbolstandard.org/"
  parent = "tools-id"
  weight = 3

[[main]]
  name = "Validator"
  url = "https://validator.sbolstandard.org/"
  parent = "tools-id"
  weight = 4

[[main]]
  name = "AI Resources"
  url = "/ai-resources/"
  parent = "tools-id"
  weight = 5

[[main]]
  name = "Community"
  weight = 50
  identifier = "community-id"

[[main]]
  name = "About the Community"
  url = "/community/"
  parent = "community-id"
  weight = 1

[[main]]
  name = "Leadership"
  url = "/community-leadership/"
  parent = "community-id"
  weight = 2

[[main]]
  name = "How to Join"
  url = "/join/"
  parent = "community-id"
  weight = 3

[[main]]
  name = "Meetings"
  url = "/community-meetings/"
  parent = "community-id"
  weight = 4

[[main]]
  name = "Industrial Consortium"
  url = "/sbol-industrial/"
  parent = "community-id"
  weight = 5

[[main]]
  name = "Governance"
  url = "/community-governance/"
  parent = "community-id"
  weight = 6

[[main]]
  name = "Publications"
  url = "/publication/"
  weight = 60
