name: Check links on live website

on:
  schedule:
    # run automatically on the first of the month
    - cron: '5 1 1 * *'
  workflow_dispatch:
    
jobs:
  check-links:
    runs-on: ubuntu-18.04
    steps:
    
      - name: Install
        run: pip3 install linkchecker
    
      - name: Check links with linkcheck
        run: linkchecker --check-extern https://sbolstandard.org/
